version: '3.3'

services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/crudApp
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    container_name: crudAppDatabase
    build:
      context: .
      dockerfile: DockerfileDb
    environment:
      POSTGRES_DB: crudApp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    restart: unless-stopped