CREATE TABLE person
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    firstname  VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    middlename VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

ALTER TABLE person
    ADD CONSTRAINT uc_person_email UNIQUE (email);
